apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-certificate
spec:
  secretName: nginx-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: nginx.diagon.ally
  dnsNames:
  - nginx.diagon.ally
  issuerRef:
    name: nginx-issuer
    kind: Issuer

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-http
  namespace: nginx-circ-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-demo-http
    protocol: TCP
    port: 80
    targetPort: 80