apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-certificate
spec:
  secretName: nginx-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: nginx.example.com
  dnsNames:
  - nginx.example.com
  issuerRef:
    name: nginx-issuer
    kind: Issuer
