apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-demo-tls
  namespace: nginx-demo
  labels:
    app: nginx-demo
spec:
  dnsNames:
  - nginx-demo.diagon.cloud
  issuerRef:
    name: nginx-demo-issuer
  secretName: nginx-demo-tls
  