apiVersion: v1
kind: Secret
metadata:
  name: my-nginx
  annotations:
    avp.kubernetes.io/path: "<path:argocd/data/argocd-vault-plugin/api_test#api>" #secret/data/my-nginx
stringData:
  MY_SECRET: <password>
